/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.cliente;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Marvin
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Principal
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.InstantiationException
     * @throws java.lang.IllegalAccessException
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    boolean individual = false;
    public Menu_Principal() throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        initComponents();
        UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        this.setSize(690, 690);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Tres en Raya");
        this.getContentPane().setBackground(Color.BLACK);
        g_tipoJuego.add(jr_UnJugador);
        g_tipoJuego.add(jr_DosJugadores);
        bt_InciarJuego.setBackground(Color.BLACK);
        inicio();
//        UIManager UI=new UIManager();
        UIManager.put("OptionPane.background",new Color(0,0,0));
        UIManager.put("Panel.background",new Color(0,0,0));
        UIManager.put("OptionPane.messageForeground",new Color(255,255,255));
        UIManager.put("OptionPane.titlePane.background",new Color(0,0,0));
        
    }
    public final void inicio(){
        jt_Jugador1.setEnabled(false);
        jt_Jugador2.setEnabled(false);
    }   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g_tipoJuego = new javax.swing.ButtonGroup();
        jl_Titulo = new javax.swing.JLabel();
        jl_PC = new javax.swing.JLabel();
        jl_Versus1 = new javax.swing.JLabel();
        jr_UnJugador = new javax.swing.JRadioButton();
        jr_DosJugadores = new javax.swing.JRadioButton();
        jl_Jugador1 = new javax.swing.JLabel();
        jl_Jugador2 = new javax.swing.JLabel();
        jt_Jugador1 = new javax.swing.JTextField();
        jt_Jugador2 = new javax.swing.JTextField();
        bt_InciarJuego = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));

        jl_Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TresEnLinea.png"))); // NOI18N

        jl_PC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/single.png"))); // NOI18N

        jl_Versus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/versus.png"))); // NOI18N

        jr_UnJugador.setBackground(new java.awt.Color(0, 0, 0));
        jr_UnJugador.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jr_UnJugador.setForeground(new java.awt.Color(255, 255, 255));
        jr_UnJugador.setText("Usuario vs PC");
        jr_UnJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jr_UnJugadorActionPerformed(evt);
            }
        });

        jr_DosJugadores.setBackground(new java.awt.Color(0, 0, 0));
        jr_DosJugadores.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jr_DosJugadores.setForeground(new java.awt.Color(255, 255, 255));
        jr_DosJugadores.setText("Usuario vs Usuario");
        jr_DosJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jr_DosJugadoresActionPerformed(evt);
            }
        });

        jl_Jugador1.setBackground(new java.awt.Color(0, 0, 0));
        jl_Jugador1.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jl_Jugador1.setForeground(new java.awt.Color(255, 255, 255));
        jl_Jugador1.setText("Jugador 1");

        jl_Jugador2.setBackground(new java.awt.Color(0, 0, 0));
        jl_Jugador2.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jl_Jugador2.setForeground(new java.awt.Color(255, 255, 255));
        jl_Jugador2.setText("Jugador 2");

        jt_Jugador1.setBackground(new java.awt.Color(51, 51, 51));
        jt_Jugador1.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jt_Jugador1.setForeground(new java.awt.Color(255, 255, 255));
        jt_Jugador1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jt_Jugador2.setBackground(new java.awt.Color(51, 51, 51));
        jt_Jugador2.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jt_Jugador2.setForeground(new java.awt.Color(255, 255, 255));
        jt_Jugador2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jt_Jugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_Jugador2ActionPerformed(evt);
            }
        });

        bt_InciarJuego.setBackground(new java.awt.Color(0, 0, 0));
        bt_InciarJuego.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        bt_InciarJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Iniciar.png"))); // NOI18N
        bt_InciarJuego.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        bt_InciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_InciarJuegoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jl_Jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(132, 132, 132)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jl_PC, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jr_UnJugador)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(112, 112, 112)
                            .addComponent(jt_Jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jt_Jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jl_Jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jr_DosJugadores)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jl_Versus1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jl_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(bt_InciarJuego)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jl_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_PC, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Versus1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jr_UnJugador)
                    .addComponent(jr_DosJugadores))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jl_Jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_Jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_Jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_Jugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(bt_InciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt_Jugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_Jugador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_Jugador2ActionPerformed

    private void bt_InciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_InciarJuegoActionPerformed
        Image image = new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB);
        if(("".equals(jt_Jugador1.getText()) && "".equals(jt_Jugador2.getText())) || ("".equals(jt_Jugador1.getText()) || "".equals(jt_Jugador2.getText())) || jt_Jugador1.getText().equals(jt_Jugador2.getText())){
            JOptionPane.showConfirmDialog(null, "Error: \n"
                + " Debe completar todos los datos"
                + " \n Los usuarios no pueden ser el mismo", "Mensaje" ,JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE,new ImageIcon(image));
        }else{
        if(jr_UnJugador.isSelected()==true){
            individual = true;
            Juego JN = new Juego(individual);
            JN.setVisible(true);
            dispose();
            Juego.jt_J1.setText(jt_Jugador1.getText());
            Juego.jt_J2.setText(jt_Jugador2.getText());
        }
        if(jr_DosJugadores.isSelected()==true){
            individual = false;
                Scanner scanner = new Scanner(System.in);
                String ip;
                int port;
                System.out.println("Please input the IP: ");
		//ip = scanner.nextLine();
                ip = "192.168.1.3";
		System.out.println("Please input the port: ");
		port = 3552;
                cliente client = new cliente(ip,port);
            Juego JN = new Juego(client,individual);
            JN.setVisible(true);
            dispose();
            Juego.jt_J1.setText(jt_Jugador1.getText());
            Juego.jt_J2.setText(jt_Jugador2.getText());

        }
        if(jr_UnJugador.isSelected()==false && jr_DosJugadores.isSelected()==false){
            JOptionPane.showConfirmDialog(null, "Debe seleccionar un modo de juego", "Mensaje" ,JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE,new ImageIcon(image));
            jt_Jugador1.setText("");
            jt_Jugador2.setText("");
        }
        }
    }//GEN-LAST:event_bt_InciarJuegoActionPerformed

    private void jr_UnJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jr_UnJugadorActionPerformed
        jt_Jugador1.setEnabled(true);
        jt_Jugador2.setEnabled(false);
        jt_Jugador2.setText("PC");
    }//GEN-LAST:event_jr_UnJugadorActionPerformed

    private void jr_DosJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jr_DosJugadoresActionPerformed
        jt_Jugador2.setText("");
        jt_Jugador1.setEnabled(true);
        jt_Jugador2.setEnabled(true);
    }//GEN-LAST:event_jr_DosJugadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Menu_Principal().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Menu_Principal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(Menu_Principal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(Menu_Principal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Menu_Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_InciarJuego;
    private javax.swing.ButtonGroup g_tipoJuego;
    private javax.swing.JLabel jl_Jugador1;
    private javax.swing.JLabel jl_Jugador2;
    private javax.swing.JLabel jl_PC;
    private javax.swing.JLabel jl_Titulo;
    private javax.swing.JLabel jl_Versus1;
    private javax.swing.JRadioButton jr_DosJugadores;
    private javax.swing.JRadioButton jr_UnJugador;
    private javax.swing.JTextField jt_Jugador1;
    private javax.swing.JTextField jt_Jugador2;
    // End of variables declaration//GEN-END:variables
}
